Drop distutils as it is deprecated
ros-infrastructure/rosdistro pull request #194
Opened 2024-12-11 06:49 UTC by MatthijsBurgh

2025-09-02 11:51 UTC, MatthijsBurgh commented
@tfoote @cottsay @mikepurvis please review this PR.

2025-09-10 15:34 UTC, tfoote requested changes
Sorry for the long delay reviewing. Thanks for contributing this. It's luckily a small tweak. 

Can you rebase to a more recent commit to get the CI runs to trigger? Otherwise this looks great to add.

2025-09-16 09:20 UTC, MatthijsBurgh commented
@tfoote rebase done

2025-10-18 08:40 UTC, MatthijsBurgh commented
The version of the git client on windows is `2.51.0.windows.2`. It is not accepted by packaging. We either have to do pre-processing. Or keep using the `distutils` module shipped by `setuptools`. @cottsay what do you think?

2025-11-19 08:43 UTC, MatthijsBurgh commented
@cottsay please respond to my previous comment

2025-11-21 19:03 UTC, cottsay commented
I don't have any silver bullets here. We clearly need to get away from distutils, so I'd guess we'll have to do some intermediate processing, which is a bummer. I'm open to suggestions.

2026-01-26 08:27 UTC, MatthijsBurgh commented
@cottsay @tfoote please approve workflow run

2026-01-26 17:14 UTC, MatthijsBurgh commented
I have no clue why the CI fails. As it runs on my account, https://github.com/MatthijsBurgh/rosdistro-1/actions/runs/21364087466

I had to restart it a few times. It looks more like a bug in GH actions than a failing pipeline.

2026-01-26 19:44 UTC, cottsay commented
> I had to restart it a few times. It looks more like a bug in GH actions than a failing pipeline.

Agreed. Looks like they're finally acknowledging that there's an issue: https://www.githubstatus.com/incidents/90hj03y5tj3c

2026-01-26 19:55 UTC, cottsay commented
This will need an update to `setup.py` and `stdeb.cfg` to include the new dependency.

2026-01-27 09:39 UTC, MatthijsBurgh commented
> This will need an update to `setup.py` and `stdeb.cfg` to include the new dependency.

@cottsay Done

2026-02-04 06:51 UTC, MatthijsBurgh commented
@cottsay please approve workflow run and review

2026-02-04 14:30 UTC, mikepurvis approved these changes

2026-02-04 15:23 UTC, cottsay commented on setup.py
> +    'install_requires': ['packaging>=17', 'PyYAML', 'setuptools'],
Is there any particular reason this is bound to version 17? We have 16.8 in RHEL 8, which appears to work.

2026-02-05 12:47 UTC, MatthijsBurgh commented on setup.py
> +    'install_requires': ['packaging>=17', 'PyYAML', 'setuptools'],
https://github.com/colcon/colcon-cmake/pull/156#discussion_r2728778851
But we don't use that feature here.

But packaging 22, adds https://github.com/pypa/packaging/commit/237ff3aa348486cf835a980592af3a59fccd6101. Before this commit, `parse` will return a `LegacyVersion`, in case of an `InvalidVersion`. These compare not correctly.

```py
LegacyVersion('0.1.0.windows.2') >  Version('0.2.0')=False
LegacyVersion('0.1.0.windows.2') >= Version('0.2.0')=False
LegacyVersion('0.1.0.windows.2') <  Version('0.2.0')=True
LegacyVersion('0.1.0.windows.2') <= Version('0.2.0')=True
Version('0.1.0') >  LegacyVersion('0.2.0.windows.2')=True
Version('0.1.0') >= LegacyVersion('0.2.0.windows.2')=True
Version('0.1.0') <  LegacyVersion('0.2.0.windows.2')=False
Version('0.1.0') <= LegacyVersion('0.2.0.windows.2')=False
```

@cottsay So to prevent really complex code, I suggest to even require packaging>=22

2026-02-05 15:32 UTC, cottsay commented on setup.py
> +    'install_requires': ['packaging>=17', 'PyYAML', 'setuptools'],
> https://github.com/colcon/colcon-cmake/pull/156#discussion_r2728778851
> But we don't use that feature here.

Sorry, my comment wasn't clear. I'm asking if we can relax it to at least `>=16.8` so that we can continue to support RHEL 8 for Humble without patching. Nothing to do with the feature requiring v17 in colcon-cmake.

> So to prevent really complex code, I suggest to even require packaging>=22

That will make the package unusable on Ubuntu Jammy (21.3), RHEL 8 (16.8) and RHEL 9 (20.9). And that's just REP 2000 platforms - I'm sure there are community platforms out there that would be affected by such a tight constraint as well.

2026-02-06 06:36 UTC, MatthijsBurgh commented on setup.py
> +    'install_requires': ['packaging>=17', 'PyYAML', 'setuptools'],
Ok I will dive into it

2026-02-20 15:42 UTC, MatthijsBurgh commented
@cottsay done, please review

2026-03-26 06:52 UTC, MatthijsBurgh commented
@cottsay friendly ping

2026-05-22 02:27 UTC, tfoote approved these changes
Thanks I think that this is good to go now.

2026-05-22 02:29 UTC, tfoote commented
@cottsay I'd like your second opinion though.

2026-05-22 04:10 UTC, merged